### ISSUE TITLE
Build issue on macOS

### ISSUE THREAD

**Issue by alexreg** [NightTsarina/python-rocksdb#11]
I having some problems building python-rocksdb with the latest version of rocksdb (6.29.3), on macOS 12.2. (I installed rocksdb via macOS Homebrew.) Basically, the issue is that there are some Cython properties on `ColumnFamilyOptions` for properties that no longer exist in the latest rocksdb, and this creates various compilation errors. I resolved the issue by manually patching the Cython code to remove those properties that are no longer present in the underlying rocksdb. However, I imagine the best solution going forwards will be to couple python-rocksdb to a specific version of rocksdb by using a Git submodule and building/using that version of rocksdb instead of the system one. That would guarantee API compatibility between python-rocksdb and rocksdb.

**Comment by NightTsarina** [comment]
Hi, thanks for your report!

I don't think it makes sense for us to import the C++ code as a submodule, but we are already running our CI pipelines with controlled versions of the library. Hopefully, when we finish some work we are currently doing in the python-rocksdb code, we will be able to look into fixing issues with the newer versions. If you feel like working on this now, patches will be most welcomed!

**Comment by alexreg** [comment]
> I don't think it makes sense for us to import the C++ code as a submodule, but we are already running our CI pipelines with controlled versions of the library.

Possibly not, though it is certainly standard practice to do this sort of thing. I have mixed views on it myself...

> If you feel like working on this now, patches will be most welcomed!

Sure, I'll submit a PR for bringing the API in line with latest rocksdb. Thanks.

**Comment by rollue** [comment]
I'm experiencing exactly the same issue on my m1 mac pro
