### ISSUE TITLE
How to specify as dependency

### ISSUE THREAD

**Issue by alexreg** [NightTsarina/python-rocksdb#12]
Is the best way to specify this fork as a dependency in `setup.cfg` the following?

```
rocksdb @ git+https://github.com/NightTsarina/python-rocksdb@v0.8.0rc2#egg=rocksdb
```

**Comment by NightTsarina** [comment]
I am not sure if you can do this in `setup.cfg`, but if you use `requirements.txt`, the format should be:
```
git+https://github.com/NightTsarina/python-rocksdb@main#egg=rocksdb
```

Note that I am specifying the `main` branch, as we are currently actively working on the code, and no new releases have been made yet.

**Comment by alexreg** [comment]
That sounds good, thanks. I think the URL format is exactly the same for `setup.cfg`, so that should work.
